### ISSUE TITLE
Font not resizing with Ctrl+ and Ctrl-

### ISSUE THREAD

**Issue by duncanabraham** [taniarascia/new-moon#1]
It's a nice theme, thanks your hard work :)

I needed to make a couple of minor changes:

if you change this line in main.less:

.CodeMirror-scroll { background: @background; color: @foreground; font-size: 12px;/\* line-height: 1.2; -webkit-font-smoothing: subpixel-antialiased; _/
 } /_*/

to this:

.CodeMirror-scroll { background: @background; color: @foreground; /\* font-size: 12px; line-height: 1.2; -webkit-font-smoothing: subpixel-antialiased; _/
 } /_*/

removing the fixed font-size,  Brackets will be able to scale the font.

**Comment by taniarascia** [comment]
Thank you for your input! I was playing around with making the font smoother and ultimately set it back to the default, but forgot to remove the font size. The issue has been fixed and uploaded as 1.0.8. I hope the theme is working well for you!

**Comment by duncanabraham** [comment]
Thanks Tania,  it's looking really good.  I've set it as my current
theme but I'm not planning on using it until Monday :)

-----Original Message-----
