### ISSUE TITLE
⚡ Hyper.js theme 

### ISSUE THREAD

**Issue by Tmeister** [taniarascia/new-moon#10]
First at all I love the theme, thank you!

I made a `port` for  [Hyperjs](https://hyper.is/), you can find the details in the [hyperterm-new-moon-theme](https://github.com/Tmeister/hyperterm-new-moon-theme) repo.

Thanks again!

**Comment by taniarascia** [comment]
Awesome! Thanks for letting me know. Feel free to submit a PR and add it to the README! :)
