### ISSUE TITLE
Unused params not distinguishable from used params in VScode

### ISSUE THREAD

**Issue by Jefwillems** [taniarascia/new-moon#12]
I'm using the vscode extension and i find it really hard to notice unused parameters in functions. (i'm using typescript but colors should be the same.)

![image](https://user-images.githubusercontent.com/10141933/53725647-b2488d00-3e6c-11e9-8138-df741f8426c1.png)

As you can see here, in the handleSmth function, the parameter color is almost exactly the same as in the handleConcept function.

**Comment by taniarascia** [comment]
As far as I know, the muted colors for unused parameters and variables is set by VSCode. Darkened some percent. I don't have any control over how much different they will look.

**Comment by Jefwillems** [comment]
Good to know, thanks!
