### ISSUE TITLE
Chrome Dev Tools new CSS key is almost invisible

### ISSUE THREAD

**Issue by sfentress** [taniarascia/new-moon#25]
When typing out a new CSS property key, the already-typed letters are rendered as black against the dark background. This makes them very difficult to see.

See example image.
<img width="1196" alt="New Moon Chrome Dev Tools CSS Prop" src="https://user-images.githubusercontent.com/35721/54450112-fae22f00-4725-11e9-9c26-fae915c239f9.png">

**Comment by taniarascia** [comment]
You have to set your theme to "Dark" on the settings panel to ensure default text is light instead of dark.
