### ISSUE TITLE
Sorry to say this, but New Moon has slowed Brackets

### ISSUE THREAD

**Issue by fluxxus** [taniarascia/new-moon#3]
I really, really love this theme, but after some playing with disabling/enabling extensions, I've seen a significant improvement in performance when using the default dark theme over your theme.

I was working on a project with a lot of files, feeling a major Brackets slow down, swiching between files, saving files, etc. Everything was slow. 

Then I first reloaded without extensions, all smooth again. Then I went by disabling one extension after another and came to the concluison: New Moon is slowing down Brackets :((

It may not be felt with just a few files, but with a lot of files opened at the same time, New Moon is definitely slowing it down.

**Comment by taniarascia** [comment]
Hmm, that's odd. I use it on a daily basis with no performance issue. But I'll go through and make a clean copy and update it.

**Comment by fluxxus** [comment]
Hi Tania, I am having seconds thoughts also now.

Maybe it is just due to the fact that I am having many files opened as working files(either in the sidepanel or with some toolbar extension). It was very late yesterday and I was already freaking out with the overall chopiness, in one moment when I disabled New Moon it seemed that it may be the reason.

But after playing again with disabling/enabling in the last half an hour, it seems that New Moon is ok :)
