### ISSUE TITLE
Any plans for VS Code ?

### ISSUE THREAD

**Issue by fluxxus** [taniarascia/new-moon#4]
I've been using your New Moon theme for Brackets since it was released, also I see that there is a port for Atom.

Lately I started thinking of switching editors, Brackets is slow sometimes, also many of extensions are not updated and left unmaintained. Atom is nice, but it is also on the slower side.

I've been using Visual Studio Code for a few days, and I really like it. It is blazing fast, startup time is non-existent. But it lacks in themes department. 

Not sure if a port from Atom would be difficult, they are both based on Electron, maybe it wouldn't be so much work :)

**Comment by taniarascia** [comment]
Hmm, I'll try out VS Code. If I end up using it, I'll have to make a New Moon for it, of course!

**Comment by fluxxus** [comment]
Ok, great !

On a side note, on Win10 64bit, the bottom editor bar is not darker color, it is white. 

On my other computer which is Win7 32bit, everything is fine. But on the Win10 laptop, the bottom bar is white, which doesn't look so good, as you can guess :)

**Comment by taniarascia** [comment]
Hmm, I'm not sure where that issue originates. I downloaded VS Code, but it seemed a bit slower than Brackets to me, so I haven't gotten around to making the theme yet!

**Comment by fluxxus** [comment]
Good to hear about your Brackets being fast. I love it more than any other editor, but in my case it is slower. And all of the articles I've found on the net talk about VS Code being the fastest.

Back to my issue. Here is the screenshot for New Moon [![Untitled-1.jpg](https://s18.postimg.org/c50e8y0ex/Untitled_1.jpg)](https://postimg.org/image/nhczqq93p/) and for Moonokai [![Untitled-2.jpg](https://s17.postimg.org/fead0ag1b/Untitled_2.jpg)](https://postimg.org/image/9dco37tez/)

Notice how the bottom bar is white.

**Comment by taniarascia** [comment]
Yeah...for the themes pack, I couldn't find a way to have it acknowledge the themes as dark mode.

**Comment by fluxxus** [comment]
Aha, got it. I will then install each theme as a solo theme !

**Comment by taniarascia** [comment]
New Moon is primarily developed on VS code these days. Two years late, I know.
