### ISSUE TITLE
VS Code: Status bar not following theme

### ISSUE THREAD

**Issue by SeanMcP** [taniarascia/new-moon#40]
## Description
The status bar on VS Code does not appear to follow the theme. Every other dark color is desaturated, but [the status bar is a dark shade of blue](https://github.com/taniarascia/new-moon/blob/03d235fc6cfb4df6001eb355ca428408cef56529/visual-studio-code/themes/new-moon.json#L38).

<img width="685" alt="Screen Shot 2019-09-09 at 4 51 32 PM" src="https://user-images.githubusercontent.com/6360367/64565653-3e5ad600-d322-11e9-96f4-5f598b8c7c67.png">

## Steps to reproduce
1. Install New Moon through Extensions tab
1. Select New Moon theme

## Comments
~~This may have something to do with the setup on my computer, but I don't have this issue with any other theme.~~ I originally filed this as a bug, but now I'm thinking it is more of a design/color decision.

**Comment by taniarascia** [comment]
@SeanMcP Good point, I'll fix it!

**Comment by taniarascia** [comment]
Updated. I never noticed because I always have status bar turned off. 😬
