### ISSUE TITLE
Style for indentation guides

### ISSUE THREAD

**Issue by ptpaterson** [taniarascia/new-moon#43]
I'm using the VS Code version and have enjoyed setting the style for indentation guide active background.

I've set to the same style as New Moon's `Keyword` color, `#ffeea6`, and I think it works well with the theme.

my setting override: 

```json
"workbench.colorCustomizations": {
    "editorIndentGuide.activeBackground": "#ffeea6"
}
```

I am honestly not sure how this affects other editors, or if the community of New Moon users would also enjoy this as a part of the theme.  But I do!

![image](https://user-images.githubusercontent.com/7998974/67587843-a757ab00-f722-11e9-8e99-1374a44e17a8.png)

**Comment by taniarascia** [comment]
Nice, I added a slightly lighter indentation color. Good idea, @ptpaterson.
