### ISSUE TITLE
VScode highlight worn colors using JS optional chaining.

### ISSUE THREAD

**Issue by victorwvieira** [taniarascia/new-moon#47]
When I use optional chaining (?.) in a JS code the VScode highlight almost the entire code with a light blue color.

Is it possible setting this new feature of JS to keep highlight correctly?

**Comment by taniarascia** [comment]
<img width="256" alt="Screen Shot 2020-06-11 at 11 19 59 PM" src="https://user-images.githubusercontent.com/11951801/84464439-19d9b480-ac3a-11ea-97d4-c79db99a63cb.png">

This is what I see. What do you see?

**Comment by victorwvieira** [comment]
@taniarascia when I use optional chaining with React, some code lines below changes to light blue:

- Using optional chaining in the attribute value.
<img width="694" alt="Screenshot 2020-06-12 at 09 41 26" src="https://user-images.githubusercontent.com/8702612/84483546-643a5000-ac91-11ea-8c1b-05c287069183.png">

- Without optional chaining
<img width="686" alt="Screenshot 2020-06-12 at 09 40 51" src="https://user-images.githubusercontent.com/8702612/84483632-859b3c00-ac91-11ea-9dc3-984745263628.png">

I don't know if is another setting in VScode that I need to change.

Thank you to help me understand this subject.

**Comment by victorwvieira** [comment]
After a researched, I identified the problem it was a babel extension in my VS Code that do not have support for optional chaining with JSX. I installed a new one [babel extension](https://marketplace.visualstudio.com/items?itemName=mgmcdermott.vscode-language-babel), now it's working perfectly.
