### ISSUE TITLE
Shipping New Moon with our IDEs

### ISSUE THREAD

**Issue by abrudz** [taniarascia/new-moon#55]
We are going to include your lovely theme into our IDEs from this coming summer. For that:
* Do you want us to include attribution? If so, let me know what and how.
* Do you want to list this on your website under "One theme for all your apps"? The links to our IDEs are: [Dyalog APL Windows IDE](https://dyalog.com) and [Dyalog APL Remote IDE (RIDE)](https://github.com/dyalog/ride)

**Comment by taniarascia** [comment]
Hiya,

Glad you like the theme! Feel free to open a PR to add it once it's ready. Attribution would be great (just my name is fine).
