### ISSUE TITLE
iTerm2 ANSI black set to light grey (making Powerlevel9k unreadable)

### ISSUE THREAD

**Issue by oli-laban** [taniarascia/new-moon#6]
Is setting ANSI black in iTerm2 to a light grey intentional?

<img width="170" alt="screen shot 2019-02-28 at 21 07 15" src="https://user-images.githubusercontent.com/16418002/53598519-e423d000-3b9c-11e9-802d-2ccd9569d228.png">

It's making Powerlevel9k unreadable, and I presume it will affect any theme that requires black to contrast with light colours.

Powerlevel9k currently:

<img width="700" alt="screen shot 2019-02-28 at 21 12 31" src="https://user-images.githubusercontent.com/16418002/53598925-e20e4100-3b9d-11e9-87db-f3f278edde1e.png">

And with ANSI black manually set to the same colour as the background:

<img width="700" alt="screen shot 2019-02-28 at 21 13 21" src="https://user-images.githubusercontent.com/16418002/53598946-f2beb700-3b9d-11e9-9773-360dcf7fe948.png">

**Comment by ajrussellaudio** [comment]
Similar problem in `htop`:

![image](https://user-images.githubusercontent.com/1347511/53602216-fbb38680-3ba5-11e9-8ab0-cd39862e83bd.png)

The green and blue bars contain light grey text that should be black.
